name: Create Plugin Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run once a month on the 1st day

# To use this workflow please create a fine-grained personal access token for your repository with:
# `contents: read and write`
# `pull requests: read and write`
# `workflows: read and write`

jobs:
  createplugin-update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.INTBOT_APP_ID }}
          private-key: ${{ secrets.INTBOT_PRIVATE_KEY }}

      - uses: grafana/plugin-actions/create-plugin-update@create-plugin-update/v2.0.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
